#!/usr/bin/env python
import sys

import settings

if __name__ == '__main__':
    if len(sys.argv) != 1:
        print >>sys.stderr, "Usage: %s" % sys.argv[0]
        sys.exit(1)

    print '\n'.join(settings.groups.keys())
