#!/usr/bin/env python

import sys
import settings

if __name__ == '__main__':
    if len(sys.argv) != 3:
        print >>sys.stderr, "Usage: %s <group> <host>" % sys.argv[0]
        sys.exit(1)

    groupname = sys.argv[1]
    if groupname not in settings.groups:
        print >>sys.stderr, "Unknown Hostgroup '%s'. Please add to settings.py" % groupname
        sys.exit(1)
    group = settings.groups[groupname]

    hostname = sys.argv[2]
    if hostname not in group:
        print >>sys.stderr, "Unknown Hostname '%s'. Please add to settings.py" % hostname
        sys.exit(1)
    host = group[hostname]

    backend = host['backend'](hostname, host)
    sys.stdout.write(backend.get_config())
