#!/usr/bin/env python

import sys
import hosts

if __name__ == '__main__':
    if len(sys.argv) != 3:
        print >>sys.stderr, "Usage: %s <group> <host>" % sys.argv[0]
        sys.exit(1)

    groupname = sys.argv[1]
    if groupname not in hosts.groups:
        print >>sys.stderr, "Unknown Hostgroup '%s'. Please add to hosts.py" % groupname
        sys.exit(1)
    group = hosts.groups[groupname]

    hostname = sys.argv[2]
    if hostname not in group:
        print >>sys.stderr, "Unknown Hostname '%s'. Please add to hosts.py" % hostname
        sys.exit(1)
    host = group[hostname]

    backend = host['backend'](hostname, host)
    print backend.get_config()
