#!/usr/bin/env python
import sys

import settings

if __name__ == '__main__':
    if len(sys.argv) != 2:
        print >>sys.stderr, "Usage: %s <group>" % sys.argv[0]
        sys.exit(1)

    groupname = sys.argv[1]
    if groupname not in settings.groups:
        print >>sys.stderr, "Unknown Hostgroup '%s'." % groupname
        sys.exit(1)
    group = settings.groups[groupname]

    print '\n'.join(group.keys())
